package com.dalaoyang.dao;

import com.dalaoyang.entity.TApplyAsyncRecord;
import com.dalaoyang.entity.TApplyAsyncRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TApplyAsyncRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    long countByExample(TApplyAsyncRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    int deleteByExample(TApplyAsyncRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    int insert(TApplyAsyncRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    int insertSelective(TApplyAsyncRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    List<TApplyAsyncRecord> selectByExampleWithBLOBs(TApplyAsyncRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    List<TApplyAsyncRecord> selectByExample(TApplyAsyncRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    TApplyAsyncRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TApplyAsyncRecord record, @Param("example") TApplyAsyncRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TApplyAsyncRecord record, @Param("example") TApplyAsyncRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TApplyAsyncRecord record, @Param("example") TApplyAsyncRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TApplyAsyncRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TApplyAsyncRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TApplyAsyncRecord record);
}