package com.dalaoyang.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_apply_async_record
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TApplyAsyncRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   审批单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.apply_id
     *
     * @mbg.generated
     */
    private String applyId;

    /**
     * Database Column Remarks:
     *   审批类型 6：部分退款， 10：产品方案申请， 11：采购付款申请， 13：物流商付款申请， 15：方案定价审批申请， 16：软装货物调价申请， 17：劳务公司付款申请， 18：销毁变卖审批
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.apply_type
     *
     * @mbg.generated
     */
    private Byte applyType;

    /**
     * Database Column Remarks:
     *   审批类型中文名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.apply_type_name
     *
     * @mbg.generated
     */
    private String applyTypeName;

    /**
     * Database Column Remarks:
     *   接口名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.service_name
     *
     * @mbg.generated
     */
    private String serviceName;

    /**
     * Database Column Remarks:
     *   重试次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.retry_times
     *
     * @mbg.generated
     */
    private Byte retryTimes;

    /**
     * Database Column Remarks:
     *   最近一次调用时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.last_call_time
     *
     * @mbg.generated
     */
    private Date lastCallTime;

    /**
     * Database Column Remarks:
     *   耗时毫秒
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.consume_time
     *
     * @mbg.generated
     */
    private Integer consumeTime;

    /**
     * Database Column Remarks:
     *   处理状态：0 待调用， 1 成功， 2 失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   补偿状态：0 待补偿， 1 补偿成功， 2 补偿失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.compensate_status
     *
     * @mbg.generated
     */
    private Byte compensateStatus;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   添加人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.create_user_id
     *
     * @mbg.generated
     */
    private Integer createUserId;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.update_user_id
     *
     * @mbg.generated
     */
    private Integer updateUserId;

    /**
     * Database Column Remarks:
     *   删除标志位,0 未删除 1已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.del_flag
     *
     * @mbg.generated
     */
    private Byte delFlag;

    /**
     * Database Column Remarks:
     *   操作入参
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.call_param
     *
     * @mbg.generated
     */
    private String callParam;

    /**
     * Database Column Remarks:
     *   操作入参
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.call_result
     *
     * @mbg.generated
     */
    private String callResult;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_async_record.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.id
     *
     * @return the value of t_apply_async_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.id
     *
     * @param id the value for t_apply_async_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.apply_id
     *
     * @return the value of t_apply_async_record.apply_id
     *
     * @mbg.generated
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.apply_id
     *
     * @param applyId the value for t_apply_async_record.apply_id
     *
     * @mbg.generated
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.apply_type
     *
     * @return the value of t_apply_async_record.apply_type
     *
     * @mbg.generated
     */
    public Byte getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.apply_type
     *
     * @param applyType the value for t_apply_async_record.apply_type
     *
     * @mbg.generated
     */
    public void setApplyType(Byte applyType) {
        this.applyType = applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.apply_type_name
     *
     * @return the value of t_apply_async_record.apply_type_name
     *
     * @mbg.generated
     */
    public String getApplyTypeName() {
        return applyTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.apply_type_name
     *
     * @param applyTypeName the value for t_apply_async_record.apply_type_name
     *
     * @mbg.generated
     */
    public void setApplyTypeName(String applyTypeName) {
        this.applyTypeName = applyTypeName == null ? null : applyTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.service_name
     *
     * @return the value of t_apply_async_record.service_name
     *
     * @mbg.generated
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.service_name
     *
     * @param serviceName the value for t_apply_async_record.service_name
     *
     * @mbg.generated
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.retry_times
     *
     * @return the value of t_apply_async_record.retry_times
     *
     * @mbg.generated
     */
    public Byte getRetryTimes() {
        return retryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.retry_times
     *
     * @param retryTimes the value for t_apply_async_record.retry_times
     *
     * @mbg.generated
     */
    public void setRetryTimes(Byte retryTimes) {
        this.retryTimes = retryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.last_call_time
     *
     * @return the value of t_apply_async_record.last_call_time
     *
     * @mbg.generated
     */
    public Date getLastCallTime() {
        return lastCallTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.last_call_time
     *
     * @param lastCallTime the value for t_apply_async_record.last_call_time
     *
     * @mbg.generated
     */
    public void setLastCallTime(Date lastCallTime) {
        this.lastCallTime = lastCallTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.consume_time
     *
     * @return the value of t_apply_async_record.consume_time
     *
     * @mbg.generated
     */
    public Integer getConsumeTime() {
        return consumeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.consume_time
     *
     * @param consumeTime the value for t_apply_async_record.consume_time
     *
     * @mbg.generated
     */
    public void setConsumeTime(Integer consumeTime) {
        this.consumeTime = consumeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.status
     *
     * @return the value of t_apply_async_record.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.status
     *
     * @param status the value for t_apply_async_record.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.compensate_status
     *
     * @return the value of t_apply_async_record.compensate_status
     *
     * @mbg.generated
     */
    public Byte getCompensateStatus() {
        return compensateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.compensate_status
     *
     * @param compensateStatus the value for t_apply_async_record.compensate_status
     *
     * @mbg.generated
     */
    public void setCompensateStatus(Byte compensateStatus) {
        this.compensateStatus = compensateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.create_time
     *
     * @return the value of t_apply_async_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.create_time
     *
     * @param createTime the value for t_apply_async_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.update_time
     *
     * @return the value of t_apply_async_record.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.update_time
     *
     * @param updateTime the value for t_apply_async_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.create_user_id
     *
     * @return the value of t_apply_async_record.create_user_id
     *
     * @mbg.generated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.create_user_id
     *
     * @param createUserId the value for t_apply_async_record.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.update_user_id
     *
     * @return the value of t_apply_async_record.update_user_id
     *
     * @mbg.generated
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.update_user_id
     *
     * @param updateUserId the value for t_apply_async_record.update_user_id
     *
     * @mbg.generated
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.del_flag
     *
     * @return the value of t_apply_async_record.del_flag
     *
     * @mbg.generated
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.del_flag
     *
     * @param delFlag the value for t_apply_async_record.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.call_param
     *
     * @return the value of t_apply_async_record.call_param
     *
     * @mbg.generated
     */
    public String getCallParam() {
        return callParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.call_param
     *
     * @param callParam the value for t_apply_async_record.call_param
     *
     * @mbg.generated
     */
    public void setCallParam(String callParam) {
        this.callParam = callParam == null ? null : callParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.call_result
     *
     * @return the value of t_apply_async_record.call_result
     *
     * @mbg.generated
     */
    public String getCallResult() {
        return callResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.call_result
     *
     * @param callResult the value for t_apply_async_record.call_result
     *
     * @mbg.generated
     */
    public void setCallResult(String callResult) {
        this.callResult = callResult == null ? null : callResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_async_record.remark
     *
     * @return the value of t_apply_async_record.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_async_record.remark
     *
     * @param remark the value for t_apply_async_record.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_async_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", applyId=").append(applyId);
        sb.append(", applyType=").append(applyType);
        sb.append(", applyTypeName=").append(applyTypeName);
        sb.append(", serviceName=").append(serviceName);
        sb.append(", retryTimes=").append(retryTimes);
        sb.append(", lastCallTime=").append(lastCallTime);
        sb.append(", consumeTime=").append(consumeTime);
        sb.append(", status=").append(status);
        sb.append(", compensateStatus=").append(compensateStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", updateUserId=").append(updateUserId);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", callParam=").append(callParam);
        sb.append(", callResult=").append(callResult);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}